default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST') {'localhost'} %>
  username: postgres
  password: <%= ENV.fetch('POSTGRES_PASSWORD') {'password'} %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development:
  <<: *default
  database: index_blog_development

test:
  <<: *default
  database: index_blog_test

production:
  <<: *default
  database: index_blog_production
  username: index_blog
  password: <%= ENV["INDEX_BLOG_DATABASE_PASSWORD"] %>
